### ISSUE TITLE
Can we add Dotsama prague?

### ISSUE THREAD

**Issue by cryptodamsky** [JosefJ/GMevents#49]
---
####################
####################
# This file is a template to create new events. In order to use it, duplicate
# the whole folder (/template) as a new folder (I.E. /my-event-name) inside of
# the /events folder, using for the folder name _only_:
# - lowercase letters
# - hyphens/dashes (-) instead of spaces
# - alphanumeric characters ('a' to 'z', '0' to '9')
# and edit the README.md file inside that new folder just created.
#
# The name of the folder will be used on the URL. Example:
# https://blockchainweek.berlin/my-event-name
#
# _Don't_ rename the new file (README.md), only edit its content.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Dotsama Prague

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Polkadot&Kusama conference focused on long term builders and general ecosystem participants.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Dotsama Prague

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  - As we have been missing Dotsama events, we’ve decided to put up a one day event with meaningful program and networking opportunities
    We are focusing on making the space more inter-connected and also making sure everybody has a chance to network at the event.
  - The conference is offering more than 8 talks, pannels, catering throughout the whole day and vibrant afterparty at the theatre with electronical music.

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2022-06-07
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2022-06-07

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '10:00'
# Time when the event ends. Can be left empty.
endTime: ''

# The URL where to acquire the tickets. Can be left empty.
tickets: https://dotsama-prague.xyz/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 24

# The name of the venue where the event will be held. Can be left empty.
venue: Jatka78, The prague market

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Jatka78, Hala číslo 7 a 8, Bubenské nábř. 306 /13, 170 00 Praha 7

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: conference

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by Vojtch159** [comment]
Hi @cryptodamsky, can you please take a look at this link and confirm that all of the information is correct before we merge the pull request? Thanks! 
https://e3808486.pragueblockchainweek.pages.dev/events/Dotsama%20Prague/
